# Generated by Django 5.1.6 on 2025-03-06 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.TextField(null=True)),
                ('duration', models.CharField(blank=True, max_length=15, null=True)),
                ('price', models.EmailField(blank=True, max_length=254, null=True)),
                ('capacity', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Block_Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.TextField(null=True)),
                ('chamber', models.CharField(blank=True, max_length=15, null=True)),
                ('temprature', models.EmailField(blank=True, max_length=254, null=True)),
                ('floor', models.TextField(blank=True, null=True)),
                ('block_no', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone1', models.CharField(blank=True, max_length=15, null=True)),
                ('email1', models.EmailField(blank=True, max_length=254, null=True)),
                ('address1', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField()),
                ('owner_firm_manager', models.TextField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('experience', models.FloatField(blank=True, max_length=255, null=True)),
                ('location', models.TextField(blank=True, max_length=255, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('package', models.CharField(blank=True, max_length=100, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.TextField(blank=True, default='Unnamed Client', null=True)),
                ('manager', models.CharField(max_length=255, null=True)),
                ('phone2', models.CharField(blank=True, max_length=15, null=True)),
                ('email2', models.EmailField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('temprature1', models.CharField(blank=True, max_length=255, null=True)),
                ('chamber_no', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColdStoreEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='Unnamed Client', max_length=255, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('item_type', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('weight_at_gate', models.CharField(max_length=50)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cold_store_entries', to='Store.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='Store.company'),
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_client', models.CharField(max_length=255, null=True)),
                ('items', models.TextField(blank=True, null=True)),
                ('units', models.TextField(blank=True, null=True)),
                ('type', models.EmailField(blank=True, max_length=254, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gates', to='Store.client')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_client', models.CharField(max_length=255, null=True)),
                ('items', models.TextField(blank=True, null=True)),
                ('new_items', models.TextField(blank=True, null=True)),
                ('old_weight', models.FloatField(blank=True, null=True)),
                ('new_weight', models.FloatField(blank=True, null=True)),
                ('chamber', models.CharField(blank=True, max_length=255, null=True)),
                ('floor', models.CharField(blank=True, max_length=255, null=True)),
                ('from_blocks', models.CharField(blank=True, max_length=255, null=True)),
                ('to_blocks', models.CharField(blank=True, max_length=255, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('payable_amount', models.FloatField(blank=True, null=True)),
                ('paid_amount', models.FloatField(blank=True, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('gate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='Store.gate')),
            ],
        ),
    ]
