# Generated by Django 5.1.6 on 2025-03-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='package',
            field=models.CharField(blank=True, choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Deactivate', 'Deactivate')], max_length=20, null=True),
        ),
    ]
