# Generated by Django 5.1.6 on 2025-03-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_alter_company_package_alter_company_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='block_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
