# Generated by Django 5.1.6 on 2025-03-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_store_block_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='temprature1',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Cold', 'Cold'), ('Hot', 'Hot')], max_length=50, null=True),
        ),
    ]
