# Generated by Django 5.1.6 on 2025-03-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_alter_store_temprature1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='block_no',
        ),
    ]
