# Generated by Django 5.1.6 on 2025-03-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_remove_store_block_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='temprature1',
        ),
        migrations.AddField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='store',
            name='structure_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Chamber, Floor, and Block Structure'),
        ),
        migrations.AddField(
            model_name='store',
            name='temperature',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Cold', 'Cold'), ('Hot', 'Hot')], max_length=50, null=True, verbose_name='Temperature Type'),
        ),
        migrations.AlterField(
            model_name='store',
            name='address2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='store',
            name='capacity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='store',
            name='chamber_no',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Chambers'),
        ),
        migrations.AlterField(
            model_name='store',
            name='email2',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='store',
            name='manager',
            field=models.CharField(max_length=255, null=True, verbose_name='Manager Name'),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(blank=True, default='Unnamed Client', max_length=255, null=True, verbose_name='Store Name'),
        ),
    ]
