# Generated by Django 5.1.6 on 2025-03-10 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_remove_store_temprature1_store_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='temperature',
            new_name='temperature1',
        ),
    ]
