# Generated by Django 5.1.6 on 2025-03-10 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_rename_temperature_store_temperature1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='temperature1',
            new_name='temprature1',
        ),
    ]
