# Generated by Django 5.1.6 on 2025-03-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_rename_temperature1_store_temprature1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['store_name'], 'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
        migrations.RemoveField(
            model_name='store',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='store',
            name='structure_data',
        ),
        migrations.AlterField(
            model_name='store',
            name='address2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Secondary Address'),
        ),
        migrations.AlterField(
            model_name='store',
            name='chamber_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chamber Number'),
        ),
        migrations.AlterField(
            model_name='store',
            name='email2',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Secondary Email'),
        ),
        migrations.AlterField(
            model_name='store',
            name='manager',
            field=models.CharField(max_length=255, null=True, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Secondary Phone'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.TextField(blank=True, default='Unnamed Client', null=True, verbose_name='Store Name'),
        ),
        migrations.AlterField(
            model_name='store',
            name='temprature1',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Cold', 'Cold'), ('Hot', 'Hot')], max_length=50, null=True, verbose_name='Temperature'),
        ),
    ]
