# Generated by Django 5.1.6 on 2025-03-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_alter_store_options_remove_store_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={},
        ),
        migrations.RemoveField(
            model_name='store',
            name='chamber_no',
        ),
        migrations.AlterField(
            model_name='store',
            name='address2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='capacity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='email2',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='manager',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.TextField(blank=True, default='Unnamed Client', null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='temprature1',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Cold', 'Cold'), ('Hot', 'Hot')], max_length=50, null=True),
        ),
    ]
