# Generated by Django 5.1.6 on 2025-03-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_store_chamber_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='chamber_details',
            field=models.JSONField(default=list),
        ),
    ]
