# Generated by Django 5.1.6 on 2025-03-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0016_alter_custom_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'SUPER_ADMIN'), ('ADMIN', 'ADMIN'), ('MANAGER', 'MANAGER'), ('GATE_MANAGER', 'GATE_MANAGER')], max_length=50),
        ),
    ]
