# Generated by Django 5.1.6 on 2025-03-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0017_alter_custom_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='custom',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'SUPER_ADMIN'), ('ADMIN', 'ADMIN'), ('MANAGER', 'MANAGER'), ('GATE_MANAGER', 'GATE_MANAGER')], default='SUPER_ADMIN', max_length=50),
        ),
    ]
