# Generated by Django 5.1.6 on 2025-03-12 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0019_alter_custom_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='custom',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='custom',
            name='company_name',
        ),
        migrations.AddField(
            model_name='custom',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='custom',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('GATE_MANAGER', 'Gate Manager')], default='SUPER_ADMIN', max_length=50),
        ),
    ]
