# Generated by Django 5.1.6 on 2025-03-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0022_item_package_delete_admin_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='new_items',
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.TextField(blank=True, default='Undefined Package', null=True),
        ),
    ]
