# Generated by Django 5.1.6 on 2025-03-13 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0023_remove_storage_new_items_alter_package_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gate',
            name='items',
        ),
        migrations.RemoveField(
            model_name='gate',
            name='select_client',
        ),
    ]
