# Generated by Django 5.1.6 on 2025-03-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0024_remove_gate_items_remove_gate_select_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='gate',
            name='items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gate',
            name='select_client',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
