# Generated by Django 5.1.6 on 2025-03-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0025_gate_items_gate_select_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'SUPER_ADMIN'), ('ADMIN', 'ADMIN'), ('MANAGER', 'MANAGER'), ('GATE_MANAGER', 'GATE_MANAGER')], default='SUPER_ADMIN', max_length=50),
        ),
    ]
