# Generated by Django 5.1.6 on 2025-03-13 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0026_alter_custom_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='Store.company'),
        ),
    ]
